name: Matrix Workflow 
on:
  push:
  
jobs:
  Matrix-test:
    runs-on: ${{matrix.os}}
    strategy:
     matrix:
      python-version: [3.8,3.9]
      os: [ubuntu-latest, windows-latest]
    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - name: setup python
      uses: actions/setup-python@v5
      with:
       python-version: ${{matrix.python-version}} 

    - name: run my script
      run: python hellomsg.py