name: Output Variables

on:
  workflow_dispatch:
   inputs:
    username:
     description: "Enter user name"
     required: true
     default: "Guest"


jobs:
  greeting_job:
    runs-on: ubuntu-latest   
    
    outputs:
      username_output: ${{steps.save_username.outputs.username}}
    steps:
      - name: "Step 1"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Udaya
          DAY_OF_WEEK: sunday
          Greeting: Hello
      - name: save username as output
        run: echo "${{github.events.inputs.username}}">> $GITHUB_OUTPUT

  create_user:
      runs-on: ubuntu-latest   
      needs: greeting_job
      steps:
        - name: greeting job with output
          run: echo "User Names is ${{needs.greeting_job.outputs.username_output}}"
