name: Demo Workflow 2   # Workflow name

on: 
 push:
  branches:
   - dev1 


jobs:
  build:              # Job name
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3   # Step 1: Checkout code
      - run: sudo mkdir ~/udaya && cd ~/udaya && sudo touch test.txt # Step 2: Run command
